### ISSUE TITLE
panic: server misbehaving

### ISSUE THREAD

**Issue by nkappler** [mtrossbach/noah-mqtt#45]
I'm getting this error upon starting the HA plugin.

With the given username and password I can login just fine at https://server.growatt.com/

I've just got my NOAH 2000 today and set it up via the app.
I'm not quite sure what the issue is.

I've already got an Shelly EM3Pro working just fine via MQTT and the Hoymiles inverter with OpenDTU as well.

<details>

{"time":"2024-12-12T13:23:12.03089171+01:00","level":"INFO","msg":"set log level","level":"INFO"}
{"time":"2024-12-12T13:23:12.032747102+01:00","level":"INFO","msg":"noah-mqtt started","version":"0.0.24","commit":"f64abc5a97401556c2f7b76089e774e3e3e666bd"}
{"time":"2024-12-12T13:23:12.033071734+01:00","level":"INFO","msg":"running as","username":"root","uid":"0"}
{"time":"2024-12-12T13:23:12.033225898+01:00","level":"INFO","msg":"connecting to mqtt broker","host":"core-mosquitto","port":1883,"clientId":"noah-mqtt","username":"addons"}
{"time":"2024-12-12T13:23:12.04068648+01:00","level":"INFO","msg":"connected to mqtt broker"}
{"time":"2024-12-12T13:23:12.040802416+01:00","level":"INFO","msg":"setting server url","url":"https://server-api.growatt.com"}
{"time":"2024-12-12T13:23:16.060901674+01:00","level":"ERROR","msg":"could not login to growatt account","error":"Post \"https://evcharge.growatt.com/ocpp/user\": dial tcp: lookup evcharge.growatt.com on 127.0.0.11:53: server misbehaving"}
{"time":"2024-12-12T13:23:16.061096567+01:00","level":"ERROR","msg":"PANIC ... waiting 15s to exit ..."}
panic: Post "https://evcharge.growatt.com/ocpp/user": dial tcp: lookup evcharge.growatt.com on 127.0.0.11:53: server misbehaving
goroutine 6 [running]:
noah-mqtt/internal/misc.Panic({0x3c2400, 0x40000bbb30})
	/home/runner/work/noah-mqtt/noah-mqtt/internal/misc/panic.go:11 +0x98
noah-mqtt/internal/polling.(*Service).Start(0x400009e8a0)
	/home/runner/work/noah-mqtt/noah-mqtt/internal/polling/service.go:38 +0xdc
main.main.func1({0x3c6f88, 0x40000c2288})
	/home/runner/work/noah-mqtt/noah-mqtt/cmd/noah-mqtt/main.go:54 +0x16c
main.connectMqtt.func1({0x3c6f88, 0x40000c2288})
	/home/runner/work/noah-mqtt/noah-mqtt/cmd/noah-mqtt/main.go:72 +0x84

</details>

**Comment by nkappler** [comment]
I'm also not sure, why the subdomain suddenly changed to evcharge.

I can't login over at evcharge.growatt.com

**Comment by mtrossbach** [comment]
evcharge.growatt.com is used for authentication using the Shine mobile app. That's why it's also used in noah-mqtt. Is this still not working for you?

**Comment by nkappler** [comment]
I've seen this panic message a few times now and then, but generally it is working now, had also issues with getting the 405, but the update to 0.25 fixed it, thank you for your work 😊
